### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by joamatab** [aisichenko/gdsfactory-workshop-ucsb#1]
You may find this useful 

https://github.com/gdsfactory/gdsfactory-photonics-training

**Comment by aisichenko** [comment]
thanks! 

to get the "open in colab" button working in https://gdsfactory.github.io/gdsfactory/ maybe you can link the button to  [gdsfactory-photonics-training](https://github.com/gdsfactory/gdsfactory-photonics-training)? right now it's https://colab.research.google.com/github/gdsfactory/gdsfactory

**Comment by joamatab** [comment]
thank you Andrei

See fix here
https://github.com/gdsfactory/gdsfactory/pull/2068
